apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
  labels:
    app: python-web-app
spec:
  selector:
    app: python-web-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP